// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Teleport 🔗</title><link rel=\"icon\" href=\"/public/link.svg\" type=\"image/svg+xml\"><script src=\"/js/htmx.min.js\"></script><script src=\"https://cdn.tailwindcss.com\"></script><script>\n      tailwind.config = {\n        theme: {\n          extend: {\n            colors: {\n              primary: \"#8B5CF6\",\n              secondary: \"#4B5563\",\n            },\n          },\n        },\n      };\n    </script></head><body class=\"h-screen bg-gradient-to-br from-gray-900 to-gray-800 text-gray-100 flex flex-col overscroll-none\"><header class=\"py-6\"><div class=\"container mx-auto px-4\"><h1 class=\"text-3xl font-bold text-center\">Tele<span class=\"text-primary\">port</span></h1></div></header><main class=\"flex-grow mx-auto px-4 py-8 flex flex-col items-center mt-10 md:mt-0 md:justify-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</main><footer class=\"py-4 text-center text-gray-400\"><p>Made with  <a class=\"underline hover:text-gray-200\" href=\"https://github.com/amitsuthar69/GoTTH\" target=\"_blank\">GoTTH Stack</a> by  <a class=\"hover:text-gray-200\" href=\"https://github.com/amitsuthar69\" target=\"_blank\">Amit Suthar</a>.</p></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
